# Dockerfile para Alerts
FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements-docker.txt .
RUN pip install --no-cache-dir -r requirements-docker.txt

# Copiar código
COPY streaming/alerts.py streaming/
COPY config/ config/
COPY logs/ logs/
COPY .env .

# Variables de entorno
ENV PYTHONPATH=/app

# Comando de inicio
CMD ["python", "streaming/alerts.py"]
